spring:
  application:
    name: TransactionManagement

  datasource:
    url: jdbc:h2:./TransactionMgmtDB
    username: admin
    password: admin123

  output:
    ansi:
      enabled: ALWAYS

  h2:
    console:
      enabled: true
      path: /h2

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
