spring:
  application:
    name: library_backend
  datasource:
    url: jdbc:h2:./Mydatabase
    username: admin
    password: admin123
  output:
    ansi:
      enabled: ALWAYS
#  sql:
#    init:
#      mode: always
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
#    properties:
#      hibernate:
#        format_sql: false

  h2:
    console:
      enabled: true
      path: /h2


server:
  port: 9091
